### ISSUE TITLE
提几个小建议，看看能不能实现

### ISSUE THREAD

**Issue by qwerttvv** [redis9219/SS_Rust_Win_Gui#1]
终于甩掉我那个开机自启vbs脚本了，先感谢一下大佬

既然gui都有了，提几个小建议看看能不能实现啊

0、这个新发现的，编辑一下，加在第一个0得了，能不能先修下，右键图标勾选【开机启动】，重启电脑后提示找不到sslocal.exe，但文件是在的。而后不做任何改动，到程序目录中手工直接双击【SS-Rust-Win-Gui.exe】，一切正常。
1、SIP002 URL的导入和导出，就是ss://XXXXXX那个连接，这个如果实现就方便很多
https://shadowsocks.org/doc/sip002.html
https://github.com/shadowsocks/shadowsocks-rust?tab=readme-ov-file#useful-tools
2、服务器自定义的备注替换到左侧服务器列表以及下方【XXX服务已连接！】提示中的IP地址部分，光看ip不好区分，而且1个服务器下会有不同的插件配置，显示备注可以快速有效的识别区分
3、能不能右键任务栏图标给选项或者左键单击图标查看当前服务器和快速切换服务器（服务器显示为自定义的备注），现在的操作需要双击打开主界面查看当前服务器，然后选择别的服务器，然后再关闭窗口，太麻烦了
4、添加一个服务器的tcp ping，点击测试后可以在左侧服务器列表直接显示对应服务器结果

另外发现一个小bug（没有过多测试，我直接改config.json去了），添加的服务器用复制按钮，如果原始为a，复制为b，那么修改b的一些配置，会导致a的对应配置随之更改。添加全新没有问题。

再有就是output.log这里日志会保存多久啊，是按文件大小来还是时间来还是一直在，啥策略的

**Comment by redis9219** [comment]
TCP ping is not yet implemented
output.log always exists, you can delete it yourself
Now you can try version 1.0.3

**Comment by qwerttvv** [comment]
Thanks, I'll update to the new version soon
